spring:
  cloud:
    gcp:
      project-id: aerial-velocity-485514-i8
      sql:
        # 1. 연결할 DB 이름
        database-name: mydb
        # 2. 인스턴스 연결 이름 (GCP 콘솔 -> 개요 에서 복사)
        # 형식: [프로젝트ID]:[리전]:[인스턴스ID]
        instance-connection-name: aerial-velocity-485514-i8:us-east1:test-rdb
        # [핵심 설정] 3. 사설 IP만 사용하여 통신 (SSL 자동 적용됨)
        ip-types: PRIVATE
        enabled: true

  config:
    import: "sm@"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${sm@db-username}
    password: ${sm@db-password}
  data:
    mongodb:
      uri: ${sm@mongo-url}
    redis:
      host: ${sm@redis-host}
      port: 6378
      ssl:
        enabled: true
        bundle: cloud-memorystore
      password: ${sm@redis-password}
  ssl:
    bundle:
      pem:
        cloud-memorystore:
          truststore:
            certificate: classpath:redis/server-ca.pem
  h2:
    console:
      enabled: false
cookie:
  secure: true
  domain: "lshkw0315.ggm.kr"
security:
  allowed-origin: "*"
jwt:
  key: ${sm@jwt-key}
  access-token-expire: ${sm@accessotken-expire}
  refresh-token-expire: ${sm@refreshtoken-expire}